name: Publish Docker Image

on:
  push:
    branches:
      - flux-training-runpod  # Trigger on every commit to this branch
  workflow_dispatch: # Allow manual runs for testing purposes

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Fetch all submodules recursively
          fetch-depth: 0         # Ensure full history is fetched

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: moizyottacom/flux:lora-training
